### ISSUE TITLE
Stopped working for latest version?

### ISSUE THREAD

**Issue by gotexis** [Hlittled/studio_3t_trial#2]
This is a error message

```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    t3/common/lic/ag.ac()Lt3/common/lic/a; @1: ireturn
  Reason:
    Type integer (current frame, stack[0]) is not assignable to 't3/common/lic/a' (from method signature)
  Current Frame:
    bci: @1
    flags: { }
    locals: { 't3/common/lic/ag' }
    stack: { integer }
  Bytecode:
    0x0000000: 03ac                                   

	at t3.common.lic.ah.am(TrialLicenseManager.java:350)
	at t3.common.lic.ah.al(TrialLicenseManager.java:120)
	at t3.common.lic.e.p(LegacyLicenseManager.java:116)
	at t3.common.lic.e.n(LegacyLicenseManager.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at t3.common.lic.i.n(LicenseManager.java:51)
	at t3.utils.a.Hh(App.java:432)
	at t3.dataman.mongodb.app.Studio3TApp.vF(Studio3TApp.java:80)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

```

**Comment by Hlittled** [comment]
2020.1.1版本部分方法名改变, 已更新

**Comment by gotexis** [comment]
Haha, that's good!
