### ISSUE TITLE
problem to use application after trial expire

### ISSUE THREAD

**Issue by kivof55409** [Hlittled/studio_3t_trial#4]
Hi, I my trial have expired, and I got issue, can you help me to fix it?

```
========== trial ==========
t3/common/lic/ag
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.crack.Agent.trial(Agent.java:122)
	at com.crack.Agent.transform(Agent.java:40)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:550)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at t3.common.lic.ah.am(TrialLicenseManager.java:350)
	at t3.common.lic.ah.al(TrialLicenseManager.java:120)
	at t3.common.lic.e.p(LegacyLicenseManager.java:116)
	at t3.common.lic.e.n(LegacyLicenseManager.java:98)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at t3.common.lic.i.n(LicenseManager.java:51)
	at t3.utils.a.Hh(App.java:432)
	at t3.dataman.mongodb.app.Studio3TApp.vF(Studio3TApp.java:80)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:61)

```

**Comment by kivof55409** [comment]
<img width="849" alt="Screenshot 2020-02-20 00 50 15" src="https://user-images.githubusercontent.com/61256126/74887348-f8974480-537a-11ea-980e-aa71895b04fe.png">
